# Generated by Django 5.2.16 on 2026-08-19 09:11

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_favorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_venues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='VenuePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('version', models.PositiveSmallIntegerField()),
                ('background_image_url', models.URLField(blank=True)),
                ('canvas_width', models.PositiveIntegerField(default=1200, validators=[django.core.validators.MinValueValidator(1)])),
                ('canvas_height', models.PositiveIntegerField(default=900, validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='events.venue')),
            ],
            options={
                'ordering': ['venue', '-version'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='venue_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='events.venueplan'),
        ),
        migrations.CreateModel(
            name='VenueSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=120)),
                ('seating_type', models.CharField(choices=[('general_admission', 'General admission'), ('reserved_seating', 'Reserved seating')], default='general_admission', max_length=24)),
                ('color', models.CharField(default='#5B5CE2', max_length=7, validators=[django.core.validators.RegexValidator(message='Rəng #RRGGBB formatında olmalıdır.', regex='^#[0-9A-Fa-f]{6}$')])),
                ('capacity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('geometry', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('venue_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='events.venueplan')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VenueSeat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_label', models.CharField(max_length=30)),
                ('seat_number', models.CharField(max_length=30)),
                ('x', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('y', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_accessible', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='events.venuesection')),
            ],
            options={
                'ordering': ['row_label', 'seat_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='venueplan',
            constraint=models.UniqueConstraint(fields=('venue', 'version'), name='unique_venue_plan_version'),
        ),
        migrations.AddConstraint(
            model_name='venueplan',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('venue',), name='unique_default_plan_per_venue'),
        ),
        migrations.AddConstraint(
            model_name='venuesection',
            constraint=models.UniqueConstraint(fields=('venue_plan', 'code'), name='unique_section_code_per_venue_plan'),
        ),
        migrations.AddConstraint(
            model_name='venueseat',
            constraint=models.UniqueConstraint(fields=('section', 'row_label', 'seat_number'), name='unique_seat_per_section_row'),
        ),
    ]
