# Generated by Django 5.2.16 on 2026-08-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_venue_created_by_venueplan_event_venue_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venueplan',
            name='version',
            field=models.PositiveSmallIntegerField(editable=False),
        ),
    ]
