# Generated by Django 5.2.16 on 2026-08-19 10:26

from django.db import migrations, models


def migrate_account_types(apps, schema_editor):
    User = apps.get_model('users', 'User')

    User.objects.filter(account_type='attendee').update(account_type='user')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_socialidentity_user_avatar_url'),
    ]

    operations = [
        migrations.RunPython(
            migrate_account_types,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('user', 'User'), ('organizer', 'Organizer'), ('admin', 'Admin')], default='user', max_length=16),
        ),
    ]
