# Generated by Django 5.2.16 on 2026-08-19 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_venue_created_by_venueplan_event_venue_plan_and_more'),
        ('ticketing', '0006_orderidempotencykey'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='venue_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ticket_types', to='events.venuesection'),
        ),
        migrations.AddConstraint(
            model_name='tickettype',
            constraint=models.UniqueConstraint(condition=models.Q(('venue_section__isnull', False)), fields=('event', 'venue_section'), name='unique_ticket_type_per_event_section'),
        ),
    ]
